[package]
name = "enc-dec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbkdf2 = { version = "0.12.2",features = ["simple"]}
sha2 = "0.10.7"